export { Header } from './header'
export { Footer } from './footer'
export { Modal } from './modal'
export { Main } from './main'
export { MethodSupport } from './method-support'
export * from './styled'
